apiVersion: apps/v1
kind: Deployment
metadata:
  name: examinator-deployment
  namespace: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: examinator
  template:
    metadata:
      labels:
        name: examinator
    spec:
      containers:
        - name: questions-provider-container
          image: application/examinator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: CONFIG_URL
              value: "http://service-config:8080/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-js-questions-deployment
  namespace: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-js-questions
  template:
    metadata:
      labels:
        name: backend-js-questions
    spec:
      containers:
        - name: js-questions-provider-container
          image: application/provider-js-questions:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: CONFIG_URL
              value: "http://service-config:8080/"
#          livenessProbe:
#            httpGet:
#              port: 8080
#              path: /actuator/health/liveness
#            readinessProbe:
#              httpGet:
#                port: 8080
#                path: /actuator/health/readiness
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-java-questions-deployment
  namespace: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-java-questions
  template:
    metadata:
      labels:
        name: backend-java-questions
    spec:
      containers:
        - name: java-questions-provider-container
          image: application/provider-java-questions:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: CONFIG_URL
              value: "http://service-config:8080/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-config-deployment
  namespace: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config-server-pod
  template:
    metadata:
      labels:
        name: config-server-pod
    spec:
      containers:
        - name: service-config-container
          image: application/config-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"