apiVersion: v1
kind: Service
metadata:
  name: examinator-service
  namespace: cloud-demo
spec:
  selector:
    name: examinator-pod
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8080