apiVersion: v1
kind: Service
metadata:
  name: provider-java-questions
  namespace: cloud-demo
spec:
  selector:
    name: backend-java-questions
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: provider-js-questions
  namespace: cloud-demo
spec:
  selector:
    name: backend-js-questions
  ports:
    - port: 8080
      targetPort: 8080
