version: '2.4'

services:
  eureka-discovery-service:
    image: application/eureka-discovery-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - 8761:8761

  examinator:
    image: application/examinator
    depends_on:
      eureka-discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8082
      DISCOVERY_URL: http://eureka-discovery-service:8761/eureka/
    ports:
      - 8082:8082

  js-questions-service:
    image: application/js-questions-service
    depends_on:
      examinator:
        condition: service_healthy
      eureka-discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8083
      DISCOVERY_URL: http://eureka-discovery-service:8761/eureka/
    ports:
      - 8083:8083

  java-questions-service:
    image: application/java-questions-service
    depends_on:
      examinator:
        condition: service_healthy
      eureka-discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8084
      DISCOVERY_URL: http://eureka-discovery-service:8761/eureka/
    ports:
      - 8084:8084