version: '2.4'

services:
  eureka-discovery-service:
    image: application/eureka-discovery-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - 8761:8761

  config-server:
    image: application/config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://eureka-discovery-service:8761/eureka/
    ports:
      - 8080:8080

  examinator:
    image: application/examinator
    depends_on:
      eureka-discovery-service:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://eureka-discovery-service:8761/eureka/
      JAVA_QUESTIONS_SERVICE_NAME: provider-java-questions
      JS_QUESTIONS_SERVICE_NAME: provider-js-questions
      CONFIG_URL: http://service-config:8080/
    ports:
      - 8093:8080

  provider-js-questions:
    image: application/provider-js-questions
    depends_on:
      examinator:
        condition: service_healthy
      eureka-discovery-service:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://eureka-discovery-service:8761/eureka/
      CONFIG_URL: http://service-config:8080/
    ports:
      - 8083:8080

  provider-java-questions:
    image: application/provider-java-questions
    depends_on:
      examinator:
        condition: service_healthy
      eureka-discovery-service:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://eureka-discovery-service:8761/eureka/
      CONFIG_URL: http://service-config:8080/
    ports:
      - 8084:8080