version: '2.4'

services:
  js_questions_service:
    image: application/js_questions_service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8083
    ports:
      - 8083:8083

  java_questions_service:
    image: application/java_questions_service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8084
    ports:
      - 8084:8084