version: '2.4'

services:
  examinator:
    image: application/examinator
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8082
    ports:
      - 8082:8082

  js_questions_service:
    image: application/js_questions_service
    depends_on:
      examinator:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8083
    ports:
      - 8083:8083

  java_questions_service:
    image: application/java_questions_service
    depends_on:
      examinator:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8084
    ports:
      - 8084:8084